services:
  - type: web
    name: sarkarbrothers-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
